### ISSUE TITLE
Seeing 404 when I press "play"

### ISSUE THREAD

**Issue by caike** [pluralsight-projects/AspNetCore-StarChartAPI#37]
Instructions on the setup phase say:

> "Press the "play" button or press F5 and you should be presented with the working project!"

but when I do that, a window opens on `http://localhost:5000/` and I see a 404 error.

**Comment by EricJFisher** [comment]
I'll clean up the instructions, there's really nothing to look at (404 until you create the Get actions) This is actually one of the short comings of this project, you can't see what you've accomplished until well into the project, and even then you'll need to use a tool like fiddler, postman, etc to really give it a test run. (I'll try to update the instructions to better reflect this)

**Comment by EricJFisher** [comment]
I updated the instructions to mention when you first start you'll get a 404 when running, and that's fine. As well as when you'll actually be able to access the service via the browser. (end of module 4)
