### ISSUE TITLE
Module 4 task 1

### ISSUE THREAD

**Issue by jonfriskics** [pluralsight-projects/AspNetCore-StarChartAPI#38]
Module: Create CelestialObjectController's Get Actions
Task 1: Create GetById Action
Instructions say: This method should have an HttpGet attribute with an value of "{id:int}" and the Name property set to "GetById".
Answer Branch: doesn't have a Name property set to GetById

**Comment by EricJFisher** [comment]
I've made the corrections for this in both the Module4Solution and Solution Branches
