### ISSUE TITLE
Not able to check in

### ISSUE THREAD

**Issue by Joaolfelicio** [pluralsight-projects/AspNetCore-StarChartAPI#59]
Hey, there is a bug on section 4, that makes me unable to check in my work, it just keeps on trying to check for a long time, after some time i get a status 524 on the console.

![ConsoleTab (2)](https://user-images.githubusercontent.com/44256600/68085050-8be45280-fe3c-11e9-9794-fcce3fd99591.PNG)

**Comment by EricJFisher** [comment]
Hello Joaolfelicio! I've taken a quick look and I'm not getting the same issue on my end. So it might have been a temporary issue earlier or something in your code. (which isn't necessarily something you've done wrong, it could also be something that would normally be fine is having issues with how we check your work someone would need to look into it)

I would suggest trying to submit the code again and see if it still throws an error and if so reach out to support@pluralsight.com. They have people working the help desk who specialize in this sort of thing 24/7. They'll be able to help you far faster than I can.

I hope this gets sorted for you quickly so you can continue learning, and thank you for taking my project!
